apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app-container
        image: jeanpierec/api-app-azure:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-service
spec:
  selector:
    app: api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
